#Time after receiving damage, during which the player can't use any commands.
timer: 15
#Should we disable using commands when a player gets hurt from the environment? (burning, drowning, etc.)
PvE: true
#Should we disable using commands when a player gets hurt from mobs?
PvM: true
#Should we let player use commands after taking damage from falling?
ignore-falling: false
#Should we disable using commands when a player gets in a fight with another player?
PvP: false
#List of worlds that ignore the plugin.
disabled-in-worlds: 
 - world_example
#Message that is sent to the players when they try to use commands after receiving damage. Supports & color codes.
message: '&cYou can not use commands when taking damage!'
